### ISSUE TITLE
What changes does this starter contain?

### ISSUE THREAD

**Issue by jspenc72** [ryharrin/angular2-rc5-cli-webpack-material-starter#1]
- Besides installing angular material, How does this project differ from a project which was generated using angular-cli@webpack
  ???

**Comment by ryharrin** [comment]
Hi there @jspenc72. Actually this is a bit outdated and I should probably take it down. When I created this, there was some additional configuration needed to start a project with angular-cli and angular material. Angular Material has since been updated to fix these issues. I'd suggest just using the CLI and installing Angular Material manually, as you'll get more updated versions that way.

**Comment by jspenc72** [comment]
Thanks for letting me know!
